### ISSUE TITLE
Meetings ?

### ISSUE THREAD

**Issue by GarethWGSMA** [camaraproject/NumberVerification#1]
Hi,

Gareth here from GSMA - do we have meetings arranged for this working group ?

Thanks,
Gareth

**Comment by DT-DawidWroblewski** [comment]
Yes - content is coming in pull request :)

**Comment by MarkusKuemmerle** [comment]
@DT-DawidWroblewski  : Would you please insert the meeting data in the Readme.md of the Sub Project?
