### ISSUE TITLE
Prepare API for CAMARA meta release 1

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/NumberVerification#107]
**Problem description**
Prepare API for CAMARA meta release 1

**Expected action**
see https://wiki.camaraproject.org/display/CAM/Meta-release+Fall24
Milestones M3 & M4 in particular

**Additional context**

**Comment by hdamker** [comment]
r1.1 with v1.0.0-rc.1 done

Next steps:
* Get #124 and #129 done
* Prepare release PR for the public release (r1.2 with v1.0.0) before August 26th (you can start now)
* Wait for final review by Release Management, Commonalities, ICM and TSC approval (for stable API release)

**Comment by bigludo7** [comment]
r1.2 with r1.0.0 done
