### ISSUE TITLE
Avoid directly commiting into the `main`-branch

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/NumberVerification#112]
**Describe the bug**
As I wanted to push a commit and create a branch based on the `main`-branch, I got the option to directly commit into the `main`-branch.
![image](https://github.com/camaraproject/NumberVerification/assets/112983658/f554a9a7-14ea-48ea-a7c2-f5cbc6ab5dbb)

**Expected behavior**
We should have here just a proposal commit or just to create a branch based on this and avoid directly commiting as proposed option for a contributer.

**Comment by hdamker** [comment]
@maxl2287 the main branch in all API and working group repositories is protected with a rule, requiring pull request and at least one code owner approval before the PR can be merged.

For me (with admin rights) it looks like this, if I try a direct commit into main it looks like this:

![image](https://github.com/user-attachments/assets/e8a47ce0-7f36-4a2c-8808-b089596b06ba)

You shouldn't be able to commit directly into main. Can you check if you by chance tried to commit into your own fork?

**Comment by maxl2287** [comment]
Closing it at it's not reproducable anymore! :)
