### ISSUE TITLE
Scope of NumberVerification for Fall24 CAMARA release

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/NumberVerification#119]
This issue shall define which issues are within scope of APIs of the Sub Project for the Fall24 release and will be regularly updated based on the decision within the OTP Validation API meetings.

Alignement with commonalities & icm
- #88 Include Authorization and authentication section in API description
- #65 Adding a '+' to the phone number before hashing should be mandatory, not optional
- #131 Align `info.description` Authorization and Authentication section with ICM v0.2.0

Enhancement
- #104 Create test definition
- #124 
- #76 Add a pattern for phoneNumber in /verify

Documentation
- #117 Adding user stories
- #129

**Comment by bigludo7** [comment]
@AxelNennker Please could take a look and propose update if I forget some pieces. Thanks Axel.

**Comment by hdamker** [comment]
Added the open PRs #124 and #129 to the scope - assuming that they are planned to be done before the pre-release?

**Comment by fernandopradocabrillo** [comment]
Added PR #131 to be included before the pre-release
