### ISSUE TITLE
Change "NUMBER_VERIFICATION.INVALID_TOKEN_CONTEXT" to "INVALID_TOKEN_CONTEXT"

### ISSUE THREAD

**Issue by AxelNennker** [camaraproject/NumberVerification#141]
**Problem description**
While reviewing 1.1 for ICM I noticed that we still  "NUMBER_VERIFICATION.INVALID_TOKEN_CONTEXT" in the yaml file once.
https://github.com/camaraproject/IdentityAndConsentManagement/issues/189#issuecomment-2314746067

We changed that to "INVALID_TOKEN_CONTEXT" some lines lower.

Why did we not change it in this line?
https://github.com/camaraproject/NumberVerification/blob/r1.1/code/API_definitions/number_verification.yaml#L271

**Expected behavior**
Change "NUMBER_VERIFICATION.INVALID_TOKEN_CONTEXT" to "INVALID_TOKEN_CONTEXT"

**Comment by bigludo7** [comment]
This is a valid point

The fix has been done by @fernandopradocabrillo last week and it appears on the [yaml](https://github.com/camaraproject/NumberVerification/blob/bigludo7/r1.2/code/API_definitions/number_verification.yaml). 
But I do not understand why this change is not reflected on the PR39 - files changed part.

**Comment by bigludo7** [comment]
Fixed in r1.2.
