### ISSUE TITLE
Convention for file names of API definition

### ISSUE THREAD

**Issue by rartych** [camaraproject/NumberVerification#142]
**Problem description**
There is currently no guidelines for file names of API definition files in CAMARA.
The initially agreed proposal is to use the convention `api-name.yaml` as a guideline for the API definition file names.

**Expected behavior**
Change the file name to `number-verification.yaml` before or as a part of release PR for M4.

**Alternative solution**
Wait for the final guidelines.

**Additional context**
See the discussion in https://github.com/camaraproject/Commonalities/issues/284.

After changing name all links should be changed in README, CHANGELOG etc.

**Comment by bigludo7** [comment]
Fixed with r1.2
