### ISSUE TITLE
Change meeting frequency - from every 2 weeks to every 4 weeks

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/NumberVerification#150]
**Problem description**
Change meeting frequency - from every 2 weeks to every 4 weeks

**Expected action**
Latest 2 meetings cancelled because too few update. But good to keep a sync.
Ask for @wrathwolf to change the Zoom Invitation.

**Additional context**

**Comment by wrathwolf** [comment]
Before I make the change, I'd like to confirm that we are moving to 06:30 UTC?

**Comment by bigludo7** [comment]
> Before I make the change, I'd like to confirm that we are moving to 06:30 UTC?

I plan to discuss both #151 and this one in the Oct'31 call with the team. I get back to you after the call.

**Comment by bigludo7** [comment]
@wrathwolf Sorry for the delay.

Decision is to shift to 7:30 UTC→ meetings would be at 9:30 during CEST and at 8:30 during CET - Thanks.
