### ISSUE TITLE
Guidelines alignment (errors and camelCase)

### ISSUE THREAD

**Issue by monamok** [camaraproject/NumberVerification#31]
I opened [PR#30](https://github.com/camaraproject/NumberVerification/pull/30) to align the API definition with following changes in the guidelines:

- Parameters should be named in lowerCamelCase. [Issue](https://github.com/camaraproject/WorkingGroups/issues/157), [Discussion](https://github.com/camaraproject/WorkingGroups/discussions/169) & [PR](https://github.com/camaraproject/WorkingGroups/pull/171).
- Adjust the schema references in the errors responses and apply the agreed solution: [Issue](https://github.com/camaraproject/WorkingGroups/issues/151) & [PR](https://github.com/camaraproject/WorkingGroups/pull/162).

I removed the restriction for error status as in commonalities there is no agreement about limiting the integer values.

**Comment by DT-DawidWroblewski** [comment]
done
