### ISSUE TITLE
MC solution and guideline alignment

### ISSUE THREAD

**Issue by monamok** [camaraproject/NumberVerification#35]
In order to keep track of what we started to discuss in today's meeting I open this issue:

Due to the last decisions that were made in commonalities (based on votes (https://github.com/camaraproject/WorkingGroups/discussions/169) related to this issue(https://github.com/camaraproject/WorkingGroups/issues/157)) the current guideline indicates that the API input and output business data would follow the [lowerCamelCase notation](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md#42-inputoutput-resource-definition)

Currently there are two flavors in Number Verification and Sim Swap APIs. The argument to include MC proposal was to have a solution that is consistent with the available solution in the market AS-IS. But now, we have to align it to the guidelines so it’s not going to be the AS-IS definition. Mobile Connect APIs (proposed in SIM Swap and Number Verification Sub-Projects) parameters follow snake_case notation and now must be changed to lowerCamelCase. 

Maybe it’s the time to reevaluate this part and see what benefits developers can get from having APIs similar to MC but not exactly aligned with them nor with 3GPP/TMF?

**Comment by DT-DawidWroblewski** [comment]
@monamok @bigludo7 @hazarig - thank you for the great discussion we had around this issue.

There's a proposal for an issue that we have to place in commonalities and later push to OpenGateway team:
(awaiting your feedback)


---
name: 🚀 Existing API standards inside CAMARA
about:  💡
---

**Context**

>What are you trying to do and how would you want to do it differently? Is it something you currently you cannot do? Is this related to an issue/problem?

Currently CAMARA lacks support for API standards, that had been already defined and are commercially available.  [SimSwap](https://github.com/camaraproject/SimSwap) [NumberVerify](https://github.com/camaraproject/NumberVerification) [OTPValidation](https://github.com/camaraproject/OTPvalidationAPI) Working Group members working on CAMARA APIs definition, which is common with Mobile Connect APIs, tackled this issue and identified a need to assess an issue inside Commonalities WG on following actions:
1. **Keep Mobile Connect APIs as they are** - MC services are standardized by GSMA, open to developers, and commercially available, so there is no need to reinvent these and adapt to CAMARA.
2. Bring Mobile Connect APIs (& others that might come, like TMF, 3GPP, etc.) as APIs available over OpenGateway in parallel to CAMARA APIs (MC APIs are following the same OAUTH/OIDC framework so this is something that both standards have in common).
3. Ensure CAMARA APIs simplicity and focus on resource definition, for the sake of simplicity for software developers.
4. Adapt local (national) breakouts to CAMARA APIs, that result from e.g. legal/regulatory conditions.

**Alternatives**

>Can you achieve the same result doing it in an alternative way? Is the alternative considerable?

1. Leave it as it is - creates confusion for developers trying to consume CAMARA APIs. Creates competing APIs - not good for developers & MNOs.
2. Archive conflicting APIs - lack of support of some APIs inside CAMARA initiative, leave it for other API standards, narrows CAMARA focus to specific 5G APIs; standards/initiatives for archived CAMARA APIs takes the lead for API development (OpenGateway **should** support other initiatives)
3. (please think of other alternatives)

**Has the feature been requested before?**

No

**If the feature request is approved, would you be willing to submit a PR?**

Yes

**Comment by bigludo7** [comment]
@DT-DawidWroblewski - Thanks !! this is good.
2 proposal in italic. Thanks for your consideration

**Comment by DT-DawidWroblewski** [comment]
Hi @bigludo7 !

I changed the content of the issue, please let me know if it is clear now and we can push it to Commonalities.

Have a nice long weekend!

**Comment by bigludo7** [comment]
Thanks @DT-DawidWroblewski  - looks good for me.

**Comment by monamok** [comment]
@DT-DawidWroblewski issue https://github.com/camaraproject/WorkingGroups/issues/200 was kind of resolved but we have still this issue open. Could you please manage the changes?
 
I can open a PR to sort out and adapt the repository if you prefer.

**Comment by DT-DawidWroblewski** [comment]
MC cleared
