### ISSUE TITLE
phoneNumber vs devicePhoneNumber

### ISSUE THREAD

**Issue by monamok** [camaraproject/NumberVerification#44]
**Problem description**
The response parameter in GET /device-phone-number endpoint is called devicePhoneNumber and it doesn't exist in the glossary.
https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Glossary.md

There are two options:

1. Rename it to phoneNumber 
2. add it to the guideline glossary?

@DT-DawidWroblewski @bigludo7 which option do you think is the better approach?

**Comment by DT-DawidWroblewski** [comment]
We don't need to add it to glossary. Let's have devicePhoneNumber.
