### ISSUE TITLE
Description for a term used in the documentation is missing

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/NumberVerification#46]
**Problem description**
In [API documentation](https://github.com/camaraproject/NumberVerification/blob/main/documentation/API_documentation/CAMARA/NUMBER_VERIFICATION_API.md), there is a line under section Authentication which says "Security access keys such as OAuth 2.0 3-legged Access Tokens used by Client applications to invoke this API with dedicated scope. **Client must use network based authentication methods** to use this service." 

The term network based authentication is not explained anywhere AFAIK and might not be known to all Camara participants.  If it is explained somewhere, and I have overseen this, kindly provide a link in the issue comment and I can gladly close this issue :)

**Expected action**
Details about the missing term should be added to the document. This term should also piggyback into authN-authZ doc.

**Additional context**

**Comment by monamok** [comment]
Hello @shilpa-padgaonkar,
there are some changes pending to be applied to this repo. This document (along all Mobile Connect related documents and definitions) must be removed. 
We already included the documentation in the API Spec, to deprecate this one;but you're absolutely right about it. We must explain the term. We'll open a PR in order to add it to the API Spec. 

Thank you for the heads up.

**Comment by shilpa-padgaonkar** [comment]
@monamok : Thank you very much for your feedback. Could you kindly piggyback your PR change also here -https://github.com/camaraproject/IdentityAndConsentManagement/issues/45

**Comment by fernandopradocabrillo** [comment]
@bigludo7 @DT-DawidWroblewski 

I think we can close this issue since it was already included into the documentation and merged

**Comment by DT-DawidWroblewski** [comment]
I'm concerned here as the Network Authentication description in [camaraproject/IdentityAndConsentManagement#55](https://github.com/camaraproject/IdentityAndConsentManagement/pull/55) doesn't give the developer a clear idea/solution of how network auth works and I see it challenging for our community to unify this.

**Comment by DT-DawidWroblewski** [comment]
all clear
