### ISSUE TITLE
Defines CAMARA scope for the CAMARA version

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/NumberVerification#49]
**Problem description**
In order to code this API and aligned our implementation we must provide scope for both operation of the CAMARA Version.

**Expected behavior**
Have scope defined for verify & device-phone-number resources.
These scopes should be  aligned with design guideline recommendation: Recommended Format: `<API_name>-<Resource>-<Permission>`

We propose following scope:
`number-verification-verify` for operation checking the phone number 
`number-verification-device-phone-number` for the operation retrieving the phone number

**Alternative solution**
No alternative solution

**Additional context**

**Comment by ECORMAC** [comment]
Hi, 
Are both operations "mandatory" or up to the consumenr on which one they choose?
Thanks.

**Comment by bigludo7** [comment]
@ECORMAC 
For me, as API implementer I have to implement both endpoint but nothing prevent to code only one operation and send a 405 for the operation not available. 
As API consumer, I'm completely free to user either one or both of these operation

@DT-DawidWroblewski @fernandopradocabrillo could you please provide feedback for the scope proposal.

**Comment by monamok** [comment]
> These scopes should be aligned with design guideline recommendation: Recommended Format: `<API_name>-<Resource>-<Permission>`
> 
> We propose following scope: `number-verification-verify` for operation checking the phone number `number-verification-device-phone-number` for the operation retrieving the phone number

For the second one, as it is a GET, I would suggest `number-verification-device-phone-number-read`. For the first one, we currently have `number-verification-verify-read` as we are not creating anything but maybe we can remove `read` and leave it as you're suggesting as it's a POST with a verb but then we're skipping <Permission>.

**Comment by DT-DawidWroblewski** [comment]
resolved
