### ISSUE TITLE
Maintainers updates

### ISSUE THREAD

**Issue by monamok** [camaraproject/NumberVerification#5]
Dear all,
I opened a [PR](https://github.com/camaraproject/NumberVerification/pull/4) to add Telefónica team to the maintainers list as it was agreed on steering committee of CAMARA project.
It's possible that there are more people from other companies that should be included. In that case please proceed.

**Comment by bigludo7** [comment]
@monamok Could you please add me for Orange
Thanks.

**Comment by DT-DawidWroblewski** [comment]
New Maintainers included.
