### ISSUE TITLE
Add documentation into API definition before release

### ISSUE THREAD

**Issue by hdamker** [camaraproject/NumberVerification#54]
**Problem description**

Agreement is that CAMARA documentation should be embedded within the OAS definition, and not separate. This reduces the effort required in maintaining documentation consistently. 

**Expected action**

Add documentation to API definition as discussed in https://github.com/camaraproject/WorkingGroups/issues/164

In addition it should be considered to move the (remaining) content of https://github.com/camaraproject/NumberVerification/blob/main/documentation/API_documentation/README.MD either into the YAML file or into the sub project README.md. 

**Additional context**

**Comment by fernandopradocabrillo** [comment]
@ECORMAC I think we can close this one too since the cleanup has been completed in PR(#58)

**Comment by hdamker** [comment]
@fernandopradocabrillo yes, thanks!
