### ISSUE TITLE
Network Authentication

### ISSUE THREAD

**Issue by mohamedsaeedstc** [camaraproject/NumberVerification#67]
**Problem Description** 
To achieve the network authentication, it's required to detect the mobile number automatically, which will be fulfilled using header enrichment (Add requester mobile number) through network for the incoming request.
The service should be exposed using HTTPS, which prevent header enrichment. 

any clue how to avoid this problem, without publish the service using HTTP (rejected from security perspective)?

Thanks

**Comment by DT-DawidWroblewski** [comment]
Hi @mohamedsaeedstc !

there are alternatives to header enrichment that are currently available.
The clue here is to find a solution which helps to identify Private IP address of a device and map it with MSISDN. Some potential options are:
1. AAA Server
2. GGSN
3. PCRF
4. RADIUS broadcast
5. SCEF

It gets more tricky when device is connected to WiFi - then it requires some special handling on a device side, e.g. force auth request to go over Mobile Data, or use EAP-AKA with a SIM.

I'm closing this issue, as this topic has been discussed several times.

I'd be happy to support, if you have more questions.

**Comment by Chintanlodariya** [comment]
> Hi @mohamedsaeedstc !
> 
> there are alternatives to header enrichment that are currently available. The clue here is to find a solution which helps to identify Private IP address of a device and map it with MSISDN. Some potential options are:
> 
> 1. AAA Server
> 2. GGSN
> 3. PCRF
> 4. RADIUS broadcast
> 5. SCEF
> 
> It gets more tricky when device is connected to WiFi - then it requires some special handling on a device side, e.g. force auth request to go over Mobile Data, or use EAP-AKA with a SIM.
> 
> I'm closing this issue, as this topic has been discussed several times.
> 
> I'd be happy to support, if you have more questions.

@DT-DawidWroblewski : by using above options we can only validate the private IP & mobile number of the subscriber but further validation with destination IP/Server would not be feasible could you pls explain little bit more on this.
