### ISSUE TITLE
Response for a number which not attached to network element (Number not verified)

### ISSUE THREAD

**Issue by ilhamnurpratama** [camaraproject/NumberVerification#70]
**Problem description**

From the .yaml documentation, regarding GET API  /device-phone-number which requires an access token to return a mobile number if a number have a valid access token. But what if a number have an access token but from our side (Telcos) detect that the number is not attach as an active number, what response does should we return.

**Expected action**

We expect a clarity regarding the response for a number which have an access token but not attach to our network element as an active number.

**Comment by bigludo7** [comment]
Hello @ilhamnurpratama 

Il the Yaml you have:

```
    PhoneNumberVerificationPermissionDenied403:
      description: |
        Client does not have sufficient permission.
        In addition to regular scenario of `PERMISSION_DENIED`, other scenarios may exist:
          - Client authentication was not via mobile network. In order to check the authentication method, AMR parameter value in the 3-legged user's access token can be used and make sure that the authentication was not either by SMS+OTP nor username/password (`{"code": "NUMBER_VERIFICATION.USER_NOT_AUTHENTICATED_BY_MOBILE_NETWORK","message": "Client must authenticate via the mobile network to use this service"}`)
          - Phone number cannot be deducted from access token context.(`{"code": "NUMBER_VERIFICATION.INVALID_TOKEN_CONTEXT","message": "Phone number cannot be deducted from access token context"}`)
     
```

Seems that the second point covers your UC isn'it?

**Comment by ilhamnurpratama** [comment]
Okay thanks a lot for the information!
